services:
  - type: web
    name: pmo-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server-pg.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3030
